import type { NextPage } from 'next';
import Head from 'next/head';
import { ButtonPrimary } from '../components/lib/Button/Button';
import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Movie Up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ButtonPrimary>ss</ButtonPrimary>
    </div>
  );
};

export default Home;
